name: mikudrome
description: Vocaloid streaming client — list and play local MV from Mikudrome server.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  video_player: ^2.8.2
  flutter_svg: ^2.0.17
  web: ^1.1.1
  file_picker: ^8.0.0+1
  http_parser: ^4.0.2
  shared_preferences: ^2.5.5
  audio_service: ^0.18.18
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/thumb.png
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: lib/assets/fonts/NotoSansJP-Regular.ttf
    - family: NotoSansSC
      fonts:
        - asset: lib/assets/fonts/NotoSansSC-Regular.ttf
